### ISSUE TITLE
cmake gporca error

### ISSUE THREAD

**Issue by digoal** [greenplum-db/gporca#11]
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/home/digoal/gporca_work \
-D XERCES_INCLUDE_DIR=/home/digoal/gp_xerces/include -D XERCES_LIBRARY=/home/digoal/gp_xerces/lib/libxerces-c.so \
-D GPOS_INCLUDE_DIR=/home/digoal/gpos_work/include/gpos -D GPOS_LIBRARY=/home/digoal/gpos_work/lib/libgpos.so.1.135 \
../

CMake Warning at cmake/FindGPOS.cmake:20 (message):
  Unable to detect GPOS version.
Call Stack (most recent call first):
  CMakeLists.txt:128 (find_package)

CMake Error at /home/digoal/cmake/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find GPOS: Found unsuitable version "0.0", but required is at
  least "1.135" (found /home/digoal/gpos_work/lib/libgpos.so)
Call Stack (most recent call first):
  /home/digoal/cmake/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGPOS.cmake:26 (find_package_handle_standard_args)
  CMakeLists.txt:128 (find_package)

**Comment by vraghavan78** [comment]
@digoal did you install Xerces and GPOS?

**Comment by digoal** [comment]
cd ~
tar -zxvf cmake-3.4.1.tar.gz 
cd cmake-3.4.1
./configure --prefix=/home/digoal/cmake
make -j 32
make install -j 32
export PATH=/home/digoal/cmake/bin:$PATH

cd ~
git clone https://github.com/greenplum-db/gpos.git
cd gpos
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/home/digoal/gpos_work ../
ctest -j 32
    100% tests passed, 0 tests failed out of 45
    Total Test time (real) =   5.87 sec
make -j 32
make install -j 32


cd ~
git clone https://github.com/greenplum-db/gporca.git

     https://xerces.apache.org/xerces-c/download.cgi
wget http://mirrors.cnnic.cn/apache//xerces/c/3/sources/xerces-c-3.1.2.tar.bz2
tar -jxvf xerces-c-3.1.2.tar.bz2
cd xerces-c-3.1.2
patch -p1 < ~/gporca/patches/xerces-c-gpdb.patch
mkdir build
cd build
../configure --prefix=/home/digoal/gp_xerces --enable-shared
make -j 32
make install -j 32
export PATH=/home/digoal/gp_xerces/bin:$PATH

cd ~/gporca
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/home/digoal/gporca_work \
-D XERCES_INCLUDE_DIR=/home/digoal/gp_xerces/include -D XERCES_LIBRARY=/home/digoal/gp_xerces/lib/libxerces-c.so \
-D GPOS_INCLUDE_DIR=/home/digoal/gpos_work/include/gpos -D GPOS_LIBRARY=/home/digoal/gpos_work/lib/libgpos.so.1.135 \
../

**Comment by hsyuan** [comment]
Don't use GPOS_INCLUDE_DIR, PREFIX, LIBRARY during build, just use default location. Please follow the README.md file.
Which OS are you using?

**Comment by vraghavan78** [comment]
@digoal please let me know if this is still an issue and I will re-open it
