### ISSUE TITLE
Executing 'make' command

### ISSUE THREAD

**Issue by VinnyPembe** [greenplum-db/gporca#141]
Hello,

I was trying to execute the 'make' command having done the following commands successfully after download the GPORCA files from GitHub:

> mkdir build
cd build
cmake -D CMAKE_INSTALL_PREFIX=/usr/local/gpdb -D XERCES_INCLUDE_DIR=/usr/local/gpdb/include -D XERCES_LIBRARY=/usr/local/gpdb/lib/libxerces-c.so -D GPOS_INCLUDE_DIR=/usr/local/gpdb/include -D GPOS_LIBRARY=/usr/local/gpdb/lib/libgpos.so ../

Unfortunately make results in the following error(s):

> [root@mdw build]# make
[  0%] Building CXX object libgpos/CMakeFiles/gpos.dir/src/common/CStackDescriptor.cpp.o
In file included from /usr/local/gpdb/include/gpos/types.h:28:0,
                 from /usr/local/gpdb/include/gpos/utils.h:18,
                 from /root/gporca/libgpos/src/common/CStackDescriptor.cpp:12:
/root/gporca/libgpos/src/common/CStackDescriptor.cpp: In member function ‘void gpos::CStackDescriptor::BackTrace(gpos::ULONG)’:
/usr/local/gpdb/include/gpos/assert.h:46:67: error: size of array ‘assert_array’ is negative
 #define GPOS_CPL_ASSERT(x)  extern int assert_array[ (x) ? 1 : -1 ]
                                                                   ^
/root/gporca/libgpos/src/common/CStackDescriptor.cpp:167:2: note: in expansion of macro ‘GPOS_CPL_ASSERT’
  GPOS_CPL_ASSERT(!"Backtrace is not supported for this platform");
  ^
/usr/local/gpdb/include/gpos/assert.h:46:40: error: unused variable ‘gpos::assert_array’ [-Werror=unused-variable]
 #define GPOS_CPL_ASSERT(x)  extern int assert_array[ (x) ? 1 : -1 ]
                                        ^
/root/gporca/libgpos/src/common/CStackDescriptor.cpp:167:2: note: in expansion of macro ‘GPOS_CPL_ASSERT’
  GPOS_CPL_ASSERT(!"Backtrace is not supported for this platform");
  ^
At global scope:
cc1plus: error: unrecognized command line option "-Wno-tautological-undefined-compare" [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [libgpos/CMakeFiles/gpos.dir/src/common/CStackDescriptor.cpp.o] Error 1
make[1]: *** [libgpos/CMakeFiles/gpos.dir/all] Error 2
make: *** [all] Error 2
[root@mdw build]# 
[root@mdw build]# 
[root@mdw build]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
[root@mdw build]# 
[root@mdw build]# 
[root@mdw build]# uname -r
4.9.7-1.el7.elrepo.x86_64

Any help on this would be appreciated.

Regards,
Vinny.

**Comment by vraghavan78** [comment]
@d @oarap can u help here

**Comment by hlinnaka** [comment]
Make sure you're building from a fresh checkout of git master, the way the platform-flags in config.h were set was broken between commits 76af8194 and 3a0921d8. That might explain the assertion on Backtrace.

You might also need to disable -Werror in the top-level CMakeLists.txt. I have to do that when building on my laptop, with a modern GCC version.

**Comment by davecramer** [comment]
I had trouble getting it to run as well, I think it's necessary to use --with-libs in configuring gpdb afterwards to use the libs in /usr/local/lib

**Comment by dhanashreek89** [comment]
@VinnyPembe 
Could you please provide the contents of `CMakeSystem.cmake` file from your `gporca/build/CMakeFiles` dir ?

**Comment by khannaekta** [comment]
We can't seem to reproduce your problem. We believe that your platform isn't being properly set in cmake. Can you provide the following to help us?

- [x] Distro/OS versions (Centos 7)
- [x] Compiler versions (GCC 4.8)
- [ ] Contents of `CMakeSystem.cmake` from somewhere under `gporca/build/CMakeFiles`
- [ ] version of ORCA you are trying to build, is it the latest?
- [ ] version of gp-xerces that you are trying link with ORCA, is it the latest?
- [ ] Steps for us to reproduce your issue

**Comment by vraghavan78** [comment]
Please reopen issue if you need more help

**Comment by wormwang** [comment]
Ubuntu 18.04 with gcc 7.3
meet the error again.

-- Build files have been written to: /root/gpdb-5.10.0/gporca/build
ninja: Entering directory `build'
[1/1073] Building CXX object libgpos/CMakeFiles/gpos.dir/src/common/CHeapObject.cpp.o
[2/1073] Building CXX object libgpos/CMakeFiles/gpos.dir/src/common/CStackDescriptor.cpp.o
FAILED: libgpos/CMakeFiles/gpos.dir/src/common/CStackDescriptor.cpp.o 
/usr/bin/c++  -Dgpos_EXPORTS -I../libgpos/include -Ilibgpos/include -g -O2 -fdebug-prefix-map=/root/gpdb-5.10.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wextra -pedantic-errors -Wno-variadic-macros -fno-omit-frame-pointer -O2 -g -DNDEBUG -g3 -fPIC   -std=gnu++98 -MD -MT libgpos/CMakeFiles/gpos.dir/src/common/CStackDescriptor.cpp.o -MF libgpos/CMakeFiles/gpos.dir/src/common/CStackDescriptor.cpp.o.d -o libgpos/CMakeFiles/gpos.dir/src/common/CStackDescriptor.cpp.o -c ../libgpos/src/common/CStackDescriptor.cpp
In file included from ../libgpos/include/gpos/types.h:28:0,
                 from ../libgpos/include/gpos/utils.h:18,
                 from ../libgpos/src/common/CStackDescriptor.cpp:12:
../libgpos/src/common/CStackDescriptor.cpp: In member function ‘void gpos::CStackDescriptor::BackTrace(gpos::ULONG)’:
../libgpos/include/gpos/assert.h:47:67: error: size of array ‘assert_array’ is negative
 #define GPOS_CPL_ASSERT(x)  extern int assert_array[ (x) ? 1 : -1 ]
                                                                   ^
../libgpos/src/common/CStackDescriptor.cpp:167:2: note: in expansion of macro ‘GPOS_CPL_ASSERT’
  GPOS_CPL_ASSERT(!"Backtrace is not supported for this platform");
  ^~~~~~~~~~~~~~~
../libgpos/include/gpos/assert.h:47:40: warning: unused variable ‘gpos::assert_array’ [-Wunused-variable]
 #define GPOS_CPL_ASSERT(x)  extern int assert_array[ (x) ? 1 : -1 ]
                                        ^
../libgpos/src/common/CStackDescriptor.cpp:167:2: note: in expansion of macro ‘GPOS_CPL_ASSERT’
  GPOS_CPL_ASSERT(!"Backtrace is not supported for this platform");
