### ISSUE TITLE
On debian install error : unrecognized comand line option '-Wno-tautological-undefined-compare'

### ISSUE THREAD

**Issue by flochman** [greenplum-db/gporca#196]
I try compile gporca on debian stretch and after ninja install or make install /I tried both install commands from gpdb and gporca readme/ I got cc1plus error : : unrecognized comand line option '-Wno-tautological-undefined-compare' [-Werror]

feew lines befour this scope error is compile error:

/home/vric/gporca-master/libnaucrates/src/md/CMDIdGPDB.ccp:337:22: error nonull argument 'this' compared to NULL [-Werrorr-nonull-compare] 

return NULL != this && !FEquals (&CMDIdGPDB::m_mdidInvalidKey);
                               ^

So is no possible to compile gporca.

Please help and fix the error.

**Comment by d** [comment]
What's your GCC version? The flag might have been renamed

**Comment by flochman** [comment]
@d 

gcc 6.3.0 20170516 (Debian 6.3.0-18)

**Comment by hsyuan** [comment]
Fixed by commit: https://github.com/greenplum-db/gporca/commit/ee5ef334c8a311d162df2c642ee159d6c9dfd7e8
Closing this issue.

**Comment by jefffleming** [comment]
I'm seeing this issue in:
libgpopt/src/base/CCTEMap.cpp line 432.
    return (NULL == &cm) ? os : cm.OsPrint(os);
and 
libgpopt/src/base/CPartIndexMap.cpp line 1074
    return (NULL == &pim) ? os : pim.OsPrint(os);

This is on Debian with gcc 6.3.0 and gcc 7.2.0
