### ISSUE TITLE
error while running sudo make on gbdb-master

### ISSUE THREAD

**Issue by rahulsingh0978** [greenplum-db/gporca#229]
In file included from include/reader.h:4:0,
                 from include/gpreader.h:4,
                 from src/gpcloud.cpp:25:
include/s3common_headers.h:8:26: fatal error: openssl/hmac.h: No such file or directory

**Comment by hsyuan** [comment]
Hi @rahulsingh0978, can you post the issue on gpdb repo?
The error has nothing to do with orca. So I will just close it.
