### ISSUE TITLE
Update Readme to tell me what gporca does and how its "modular"

### ISSUE THREAD

**Issue by fresheneesz** [greenplum-db/gporca#238]
I'm interested in modular optimizations and came across this. But I'm not familiar with Orca, and this readme doesn't seem to explain to me what the motivation behind gporca is or how it works. It seems like the readme focuses on how to contribute to it, but I want to know how to use it. Can someone please update the readme to be clearer about what gporca is and how its used (example use cases)?

Is this a system where users of gporca can write individual query optimizers and chain them to create an optimization suite that optimizes their queries?

**Comment by hsyuan** [comment]
GPDB is an example on how to integrate GPORCA optimizer into a Posgres like database system. 
Check this out:
https://github.com/greenplum-db/gpdb/tree/master/src/backend/gpopt

**Comment by vraghavan78** [comment]
Updated the README with our white papers and blogs. More to come. Thanks for bring this up.

https://github.com/greenplum-db/gporca/pull/257
