### ISSUE TITLE
README fails to disclose required minimum version of CMake

### ISSUE THREAD

**Issue by schubert** [greenplum-db/gporca#248]
On a fresh clone of gporca, following the README instructions results in the following problem:

```
CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
  CMake 3.0 or higher is required.  You are running version 2.8.12.2

-- Configuring incomplete, errors occurred!
[WARNING] Build command cmake -GNinja ../ exited with code 1. Please verify that the build completed successfully.
[WARNING] No files were emitted. This may be due to a problem with your configuration
or because no files were actually compiled by your build command.
Please make sure you have configured the compilers actually used in the compilation.
 For more details, please look at: 
    /vagrant/gporca/build/cov-int/build-log.txt
```

This means a user (me) wasted time installing the wrong version of CMake. That's no fun.

P.S. secondary issue: instead of requiring a "mkdir build" why not just include an empty `build` folder with `.gitkeep`?

**Comment by dhanashreek89** [comment]
README mentions it in it's initial portion:
```
GPORCA supports various build types: debug, release with debug info, release. On x86 systems, GPORCA can also be built as a 32-bit or 64-bit library. You'll need CMake 3.0 or higher to build GPORCA. Get it from cmake.org, or your operating system's package manager.
```

However it would be good to state in the following section as well ..
`ORCA is built with CMake, ...`

**Comment by schubert** [comment]
FWIW perhaps providing basic dependency instructions for various OS's would help.

For CentOS7:

```
$ sudo yum -y install epel-release
$ sudo yum -y install cmake3
```

and call `cmake3` instead of `cmake`

**Comment by schubert** [comment]
@dhanashreek89 yeah I completely missed that because I expected it in that other line you called out.

**Comment by d** [comment]
@schubert I'm vehemently against mentioning `yum install` in the readme for two reasons:

1. If we mention `yum install`, it'll be only fair to mention `dnf install` (which replaces `yum` in the future), `apt-get install`, `brew install`, and `emerge`.
1. The CentOS repository is grossly out of date for our build tool chain. I'm actually shocked that `cmake` (version 3+) comes from EPEL, not the more official repo
1. The CMake project actually takes care of most of this for us, [providing binary downloads](https://cmake.org/download/) for 32 and 64 -bits Windows, macOS, and 64-bit GNU/Linux
1. The `CMakeLists.txt` file is self-documenting (with `cmake_minimum_required(VERSION)`)

I propose we completely be out of the business of telling the user how to install their package, and link to the [CMake project](https://cmake.org).

Back to your original question, I'm ambivalent whether we should even mention the minimal required CMake version in our README, given it's described in `CMakeLists.txt`.

**Comment by hawqtoolsmiths** [comment]
I would strongly suggest we mention and minimal requirements in the README.  Having the requirements burried in the CMakeLists.txt isn’t going to help folks who are just interested in compiling ORCA but not working on it.  I agree that specifying how to install should be avoided, but let’s at least be upfront about what’s needed to install and run our software.

~ mike
