### ISSUE TITLE
AddJoinOrder time complexity is O(N*K)

### ISSUE THREAD

**Issue by hsyuan** [greenplum-db/gporca#266]
In function `AddJoinOrder`,  we want to store the top K cheapest join order out of N alternatives. We use linear search to find the target to evict if the number of alternatives N is greater than K, the time complexity is `O(N*K)`.

But in fact we should use max heap, with which the time complexity is `O(N*log(K))`.

```c++
// we have stored K expressions, evict worst expression
for (ULONG ul = 0; !fAddJoinOrder && ul < ulResults; ul++)
{
	CExpression *pexpr = (*m_pdrgpexprTopKOrders)[ul];
	CDouble *pd = m_phmexprcost->PtLookup(pexpr);
	GPOS_ASSERT(NULL != pd);

	if (dCost < *pd)
	{
		// found a worse expression
		fAddJoinOrder = true;
		iReplacePos = ul;
	}
}
```
What's worse, the code doesn't guarantee we can get the top K cheapest join order. Let K be 5, and the current 5 join order costs are:
2, 3, 4, 5, 6

If we have another join order with cost of 2, the above code will evict 3. But in fact we should evict 6.

**Comment by vraghavan78** [comment]
not going to fix this anytime soon.
