### ISSUE TITLE
Orca GUC optimizer_join_order_threshold doesn't take effect

### ISSUE THREAD

**Issue by hsyuan** [greenplum-db/gporca#268]
The GPDB GUC `optimizer_join_order_threshold` (Orca CHint param m_ulJoinOrderDPLimit, btw, which is really bad, inconsistent naming) is only valid when its value is less than `GPOPT_DP_JOIN_ORDERING_SIZE_THRESHOLD` (10). The orca config param is overrode by https://github.com/greenplum-db/gporca/blame/master/libgpopt/src/xforms/CJoinOrderDP.cpp#L1059

**Comment by bhuvnesh2703** [comment]
we should set the max value of optimizer_join_order_threshold to 10/12 after removing this macro. It will be then completely controlled by the GUC which is tunable then a hardcoded macro..

**Comment by bhuvnesh2703** [comment]
PR https://github.com/greenplum-db/gpdb/pull/4046, https://github.com/greenplum-db/gporca/pull/276

**Comment by hsyuan** [comment]
fixed by commit: https://github.com/greenplum-db/gporca/commit/0171e2be91648380b03d598c7033a513df8ad06b
