### ISSUE TITLE
I am getting following when i install using ninja install -C build

### ISSUE THREAD

**Issue by Dishcreate** [greenplum-db/gporca#270]
ninja: Entering directory `build'
[1/2] Linking CXX executable server/gporca_test
FAILED: server/gporca_test

**Comment by dhanashreek89** [comment]
Hello @Dishcreate 

Could you please provide the steps you are following to build and install GPORCA ?

**Comment by Dishcreate** [comment]
I have follow below steps 
git clone https://github.com/greenplum-db/gporca.git
cd gporca
cmake -GNinja -H. -Bbuild
ninja install -C build

**Comment by dhanashreek89** [comment]
Hi @Dishcreate 
I could not reproduce the error you reported.
Are you still facing the issue? If yes, could you provide some more environmental details that will help us reproduce and troubleshot the error ?

**Comment by Dishcreate** [comment]
I have faced some another error it was mention in here #4039

**Comment by Dishcreate** [comment]
[](url)
