### ISSUE TITLE
O(N^2) Time complexity of CUtils::FMatchChildrenUnordered

### ISSUE THREAD

**Issue by hsyuan** [greenplum-db/gporca#295]
CUtils::FMatchChildrenUnordered is used by CUtils::FEqual, which is used extensively in Orca. But the time complexity is O(N^2), we can do better to O(N*lgN), or even O(N).

**Comment by vraghavan78** [comment]
Thanks created an internal story

**Comment by d** [comment]
Is that a hotspot ?

**Comment by vraghavan78** [comment]
Closing this since it is not a hotspot.
