### ISSUE TITLE
make error on Ubuntu 18.04 with gcc 7.3

### ISSUE THREAD

**Issue by wormwang** [greenplum-db/gporca#392]
Ubuntu 18.04 with gcc 7.3
meet the error again.

-- Build files have been written to: /root/gpdb-5.10.0/gporca/build
ninja: Entering directory `build'
[1/1073] Building CXX object libgpos/CMakeFiles/gpos.dir/src/common/CHeapObject.cpp.o
[2/1073] Building CXX object libgpos/CMakeFiles/gpos.dir/src/common/CStackDescriptor.cpp.o
FAILED: libgpos/CMakeFiles/gpos.dir/src/common/CStackDescriptor.cpp.o
/usr/bin/c++ -Dgpos_EXPORTS -I../libgpos/include -Ilibgpos/include -g -O2 -fdebug-prefix-map=/root/gpdb-5.10.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wextra -pedantic-errors -Wno-variadic-macros -fno-omit-frame-pointer -O2 -g -DNDEBUG -g3 -fPIC -std=gnu++98 -MD -MT libgpos/CMakeFiles/gpos.dir/src/common/CStackDescriptor.cpp.o -MF libgpos/CMakeFiles/gpos.dir/src/common/CStackDescriptor.cpp.o.d -o libgpos/CMakeFiles/gpos.dir/src/common/CStackDescriptor.cpp.o -c ../libgpos/src/common/CStackDescriptor.cpp
In file included from ../libgpos/include/gpos/types.h:28:0,
from ../libgpos/include/gpos/utils.h:18,
from ../libgpos/src/common/CStackDescriptor.cpp:12:
../libgpos/src/common/CStackDescriptor.cpp: In member function ‘void gpos::CStackDescriptor::BackTrace(gpos::ULONG)’:
../libgpos/include/gpos/assert.h:47:67: error: size of array ‘assert_array’ is negative
#define GPOS_CPL_ASSERT(x) extern int assert_array[ (x) ? 1 : -1 ]
^
../libgpos/src/common/CStackDescriptor.cpp:167:2: note: in expansion of macro ‘GPOS_CPL_ASSERT’
GPOS_CPL_ASSERT(!"Backtrace is not supported for this platform");
^~~~~~~~~~~~~~~
../libgpos/include/gpos/assert.h:47:40: warning: unused variable ‘gpos::assert_array’ [-Wunused-variable]
#define GPOS_CPL_ASSERT(x) extern int assert_array[ (x) ? 1 : -1 ]
^
../libgpos/src/common/CStackDescriptor.cpp:167:2: note: in expansion of macro ‘GPOS_CPL_ASSERT’
GPOS_CPL_ASSERT(!"Backtrace is not supported for this platform");

**Comment by sambitesh** [comment]
Hi @wormwang,

    Thanks for trying out ORCA. We have tried compiling this on gcc-7.4.0 and it works fine. Can you try upgrading your compiler to gcc-7.4.0 and see if it fixes the problem?

Thanks

**Comment by vraghavan78** [comment]
Closing issue. Please let us know if the issue persists in gcc-7.4.0
