### ISSUE TITLE
unable build on gcc 6.1.1 due to _GLIBCXX_INCLUDE_NEXT_C_HEADERS 

### ISSUE THREAD

**Issue by armgong** [greenplum-db/gporca#73]
on gcc 6.1.1  
https://gcc.gnu.org/ml/libstdc++/2016-01/msg00025.html

**Comment by armgong** [comment]
this is a temporary and very ugly fix for build on gcc 6.1.1. 
1  In /usr/local/include/gpos/base.h add  one line ,this should be gpos issue, but I report here
  ~~~c
     12 #ifndef GPOS_base_H
     13 #define GPOS_base_H
     14 #define _GLIBCXX_INCLUDE_NEXT_C_HEADERS 1
     15 #define ALLOW_memcpy
  ~~~
2  In gporca dir  CMakeLists.txt change  line 44 add std=gnu++98  --Wno-address -Wno-error=address  -Wno-nonnull-compare
 ~~~cmake
      42 check_cxx_compiler_flag("-Wall" COMPILER_HAS_WALL)
      43 if (COMPILER_HAS_WALL)
      44   SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -std=gnu++98  --Wno-address -Wno-error=address  -Wno-nonnull-compare")
      45 endif()
 ~~~

**Comment by vraghavan78** [comment]
thank you for bring this up we will take a look.

**Comment by d** [comment]
Thanks for letting us know. We'll fix it when we bump to GCC6.
